"""Generate native and CSS geometry from one DIP model; --check rejects drift."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    values = json.loads((ROOT / 'geometry.json').read_text())
    header = '// Generated by scripts/generate-geometry.py. Edit geometry.json.\n#pragma once\nnamespace soulu::geometry {\n'
    css = '/* Generated by scripts/generate-geometry.py. Edit geometry.json. */\n:root {\n'
    for name, value in values.items():
        token = ''.join('-' + c.lower() if c.isupper() else c for c in name)
        header += f'inline constexpr int {name} = {value};\n'
        css += f'  --geometry-{token}: {value}px;\n'
    return {'cef/soulu/geometry.h': header + '}\n', 'ui/geometry.css': css + '}\n'}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            assert path.read_text() == content, f'{name} is stale'
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
