"""Generate web and native metrics from the one semantic model."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    tokens = json.loads((ROOT / 'typography.json').read_text())
    css = '/* Generated by scripts/generate-typography.py. Edit typography.json. */\n'
    for weight, name in ((400,'Regular'),(500,'Medium'),(600,'SemiBold')):
        css += ('@font-face{font-family:Onest;src:url("fonts/Onest-'+name+'.ttf") format("truetype");'
                f'font-weight:{weight};font-style:normal;font-display:block;}}\n')
    css += ':root{\n  --font-ui:Onest,"Segoe UI Emoji","Segoe UI Symbol",sans-serif;\n'
    for name,(size,line,weight) in tokens.items():
        css += f'  --type-{name}:{weight} {size}px/{line}px var(--font-ui);\n'
    # These are graphic glyph sizes, not extra text roles.
    css += '  --glyph-tiny:8px;--glyph-medium:20px;--glyph-large:32px;\n}\n'
    css += '''html,body{font:var(--type-body);letter-spacing:normal;font-synthesis:none}
button{font:var(--type-control)}
input,textarea,select{font:var(--type-body)}
:where(h1):not(:where(.reader-article *)){font:var(--type-heading1)}
:where(h2):not(:where(.reader-article *)){font:var(--type-heading2)}
:where(h3,h4,h5,h6):not(:where(.reader-article *)){font:var(--type-heading3)}
:where(small):not(:where(.reader-article *)){font:var(--type-caption)}
:where(strong,b){font-weight:500}
html:not(.typography-ready) body{visibility:hidden}
.shortcut-initial{display:grid;place-items:center;font:var(--type-heading3);color:#89919e}
.country-code{display:inline-grid;place-items:center;font:var(--type-compactControl);color:#fff;background:#344256;border-radius:3px;min-width:28px;height:20px}
/* Reader article remains a separate user-controlled content mode. */
.reader-article strong,.reader-article b{font-weight:bold}
.reader-article{font-synthesis:weight style}
.reader-toolbar,.reader-settings,.reader-link-menu{font-family:var(--font-ui);font-synthesis:none}
/* Shared semantic roles for inherited text and compact action menus. */
.bookmark-context .nav-action,.bookmark-actions .nav-action,.reader-link-menu button,.site-menu-content>button{font:var(--type-compactControl)}
.overview-caption strong{font:var(--type-compactControl)}
.overview-caption small,.reader-notice{font:var(--type-caption)}
.site-heading strong{font:var(--type-heading3)}
.reader-toolbar button{font:var(--type-compactControl)}
.soulu-type-tooltip{position:fixed;z-index:2147483647;pointer-events:none;max-width:min(360px,calc(100vw - 16px));padding:7px 10px;border:1px solid var(--line,#ccd0d7);border-radius:8px;background:var(--surface,var(--panel,var(--solid,#fff)));color:var(--text,var(--fg,#242529));box-shadow:0 4px 16px #0002;overflow-wrap:anywhere;font:var(--type-caption)}
.soulu-type-tooltip[hidden]{display:none}
'''
    header = '''// Generated by scripts/generate-typography.py. Edit typography.json.
#pragma once
namespace soulu::typography {
struct Metrics { float size, lineHeight; int weight; };
'''
    font_metrics=json.loads((ROOT/'ui/fonts/manifest.json').read_text())['metrics']
    header += f'inline constexpr float onestAscent={font_metrics["ascent"] / font_metrics["unitsPerEm"]}f;\n'
    header += f'inline constexpr float onestDescent={font_metrics["descent"] / font_metrics["unitsPerEm"]}f;\n'
    for name,(size,line,weight) in tokens.items():
        def literal(value):
            text = format(float(value), '.6f').rstrip('0').rstrip('.')
            return (text if '.' in text else text + '.0') + 'f'
        header += f'inline constexpr Metrics {name}{{{literal(size)},{literal(line)},{weight}}};\n'
    header += '}\n'
    return {'ui/typography.css':css, 'installer/typography_metrics.h':header,
            'cef/soulu/typography_metrics.h':header}

if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,text in outputs().items():
        path=ROOT/name
        if args.check:
            assert path.read_text(encoding='utf-8')==text, f'Stale generated typography: {name}'
        else: path.write_text(text,encoding='utf-8')
