// Generated by scripts/generate-geometry.py. Edit geometry.json.
#pragma once
namespace soulu::geometry {
inline constexpr int mainToolbar = 58;
inline constexpr int mainContainer = 38;
inline constexpr int mainCapsule = 32;
inline constexpr int mainTarget = 32;
inline constexpr int classicToolbar = 82;
inline constexpr int classicTarget = 30;
inline constexpr int classicCaption = 48;
inline constexpr int glyph = 16;
inline constexpr int captionWidth = 42;
inline constexpr int bookmarks = 28;
}
