(() => {
 'use strict';
 const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const invoke=(action,payload=null)=>new Promise((resolve,reject)=>window.cefQuery({request:JSON.stringify({action,payload}),persistent:false,onSuccess:v=>resolve(v?JSON.parse(v):null),onFailure:()=>reject(Error('bridge'))}));
 let state={},weather={},open=null,listening=false,voiceToken=0,weatherKey='',alive=true;
 const t=key=>(window.souluHomeStrings[state.language==='en'?'en':'ru'])[key];
 const paths={clear:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',cloudy:'<path d="M6 18h13a4 4 0 0 0 0-8 6 6 0 0 0-11-2 5 5 0 0 0-2 10Z"/>',rain:'<path d="M6 15h13a4 4 0 0 0 0-8 6 6 0 0 0-11-2 5 5 0 0 0-2 10ZM7 18l-1 3m7-3-1 3m7-3-1 3"/>',snow:'<path d="M6 14h13a4 4 0 0 0 0-8 6 6 0 0 0-11-2 5 5 0 0 0-2 10ZM6 18v4m-2-2h4m5-2v4m-2-2h4m5-2v4m-2-2h4"/>',storm:'<path d="M6 14h13a4 4 0 0 0 0-8 6 6 0 0 0-11-2 5 5 0 0 0-2 10ZM13 14l-4 5h5l-3 4"/>',fog:'<path d="M6 12h13a4 4 0 0 0 0-8 6 6 0 0 0-11-2 5 5 0 0 0-2 10ZM3 17h18M5 21h14"/>',site:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>'};
 function condition(c){return c===0?'clear':c<=2?'partly':c===3?'cloudy':[45,48].includes(c)?'fog':c>=95?'storm':[75,86].includes(c)?'heavySnow':c>=71&&c<=86?'snow':[65,67,82].includes(c)?'heavyRain':c>=51?'rain':'unknown';}
 function icon(kind){const n=document.createElementNS('http://www.w3.org/2000/svg','svg');n.setAttribute('viewBox','0 0 24 24');n.setAttribute('aria-hidden','true');n.innerHTML=paths[{partly:'cloudy',heavyRain:'rain',heavySnow:'snow',unknown:'cloudy'}[kind]||kind]||paths.cloudy;return n;}
 function close(restore=false){if(!open)return;const previous=open;$(previous+'Panel').hidden=true;$(previous+'Toggle').setAttribute('aria-expanded','false');open=null;if(restore)$(previous+'Toggle').focus();}
 function toggle(id){if(open===id){close(true);return;}close();open=id;$(id+'Panel').hidden=false;if(id==='weather')refreshWeather(true);$(id+'Toggle').setAttribute('aria-expanded','true');if(id==='provider')$(state.homeProvider==='perplexity'?'perplexityOption':'googleOption').focus();else if(id==='favorites')$('favoritesGrid').querySelector('a')?.focus();}
 const report=()=>$('status').textContent=t('error');
 const navigate=value=>{close();return invoke('home.navigate',value).catch(report);};
 function favorites(){const rows=state.favorites||[];$('favoritesGrid').replaceChildren();$('favoritesEmpty').hidden=rows.length>0;$('favoritesEmpty').textContent=t('empty');for(const row of rows){let u;try{u=new URL(row.url);if(!['https:','http:'].includes(u.protocol))continue;}catch{continue;}const a=el('a',undefined,'favorite');a.href=u.href;a.title=row.title||u.hostname;const fallback=el('span',undefined,'fallback');fallback.append(icon('site'));a.append(fallback,el('span',row.title||u.hostname));const image=el('img');image.alt='';image.referrerPolicy='no-referrer';image.onload=()=>{if(alive&&a.isConnected)fallback.replaceWith(image);};image.onerror=()=>{image.onerror=null;};let source='';try{const candidate=new URL(row.favicon||'/favicon.ico',u);if(candidate.protocol==='https:'||candidate.protocol==='data:'&&candidate.href.startsWith('data:image/'))source=candidate.href;}catch{}if(source)image.src=source;a.onclick=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey||e.shiftKey)invoke('home.favorite',{id:row.id,background:!e.shiftKey}).catch(report);else navigate(u.href);};a.onauxclick=e=>{if(e.button===1){e.preventDefault();invoke('home.favorite',{id:row.id,background:true}).catch(report);}};$('favoritesGrid').append(a);}}
 function temperature(v){return Number.isFinite(v)?(v>0?'+':'')+Math.round(v)+'°':'—';}
 function renderWeather(){const ok=weather.status==='ready'||weather.status==='stale',current=weather.current||{},kind=condition(current.weather_code);$('weatherIcon').replaceChildren(icon(kind));$('weatherSummary').textContent=ok?temperature(current.temperature_2m)+' '+(weather.city||''):t(weather.status==='loading'?'loading':'unavailable');const box=$('weatherDetail');box.replaceChildren();if(!ok){box.append(el('p',t('unavailable'),'weather-note'));return;}box.append(el('strong',weather.city));const now=el('div',undefined,'weather-current');now.append(icon(kind),el('span',temperature(current.temperature_2m),'weather-temperature'),el('span',t(kind)));box.append(now);const metrics=el('div',undefined,'weather-metrics');const unit=state.homeWeatherUnits==='fahrenheit'?'°F':'°C';for(const [label,value] of [['highLow',temperature(weather.daily?.temperature_2m_max?.[0])+' / '+temperature(weather.daily?.temperature_2m_min?.[0])],['feels',temperature(current.apparent_temperature)+unit.slice(1)],['wind',Number.isFinite(current.wind_speed_10m)?Math.round(current.wind_speed_10m)+' '+t('windUnit'):'—'],['humidity',Number.isFinite(current.relative_humidity_2m)?current.relative_humidity_2m+'%':'—'],['precipitation',Number.isFinite(current.precipitation)?current.precipitation+' '+t('rainUnit'):'—']])metrics.append(el('span',t(label)+': '+value));box.append(metrics);const forecast=el('div',undefined,'weather-forecast'),daily=weather.daily||{};for(let i=1;i<Math.min(6,daily.time?.length||0);i++){const day=el('div',undefined,'forecast-day');day.append(el('span',new Date(daily.time[i]+'T12:00:00').toLocaleDateString(state.language==='en'?'en':'ru',{weekday:'short'})),icon(condition(daily.weather_code?.[i])),el('span',temperature(daily.temperature_2m_min?.[i])+' / '+temperature(daily.temperature_2m_max?.[i])),el('span',(daily.precipitation_probability_max?.[i]??'—')+'%'));forecast.append(day);}box.append(forecast);if(weather.status==='stale')box.append(el('p',t('stale'),'weather-note'));const note=el('div',undefined,'weather-note'),link=el('a','Open-Meteo');link.href='https://open-meteo.com/';link.onclick=e=>{e.preventDefault();navigate(link.href);};note.append(link);box.append(note);}
 function refreshWeather(force=false){const key=JSON.stringify([state.homeWeatherCity,state.homeWeatherMode,state.homeWeatherUnits,state.language,state.homeLocationAllowed]);if(key===weatherKey&&(!force||weather.status==='ready'&&Date.now()/1000-weather.fetchedAt<900))return;weatherKey=key;if(!['ready','stale'].includes(weather.status)){weather={status:'loading'};renderWeather();}invoke('home.weather').then(data=>{if(alive&&key===weatherKey){weather=data;renderWeather();}}).catch(()=>{if(alive&&key===weatherKey){weather={status:'unavailable'};renderWeather();}});}
 function apply(next){state=next;document.documentElement.lang=state.language==='en'?'en':'ru';document.body.dataset.theme=state.resolvedTheme||'system';$('query').placeholder=t('input');$('query').setAttribute('aria-label',t('input'));for(const [id,label] of [['providerToggle','provider'],['favoritesToggle','favorites'],['weatherToggle','weather'],['providerPanel','provider'],['favoritesPanel','favorites'],['weatherPanel','weather']])$(id).setAttribute('aria-label',t(label));$('voice').setAttribute('aria-label',t(listening?'cancelVoice':'voice'));const provider=state.homeProvider==='perplexity'?'perplexity':'google';$('providerName').textContent=provider==='google'?'Google':'Perplexity';$('providerIcon').src='providers/'+provider+(provider==='google'?'.png':'.ico');for(const id of ['google','perplexity'])$(id+'Option').setAttribute('aria-selected',String(provider===id));favorites();renderWeather();refreshWeather();}
 window.souluHomeApply=apply;window.souluHomeFocus=()=>$('query').focus({preventScroll:true});
 $('search').onsubmit=e=>{e.preventDefault();const value=$('query').value.trim();if(value)navigate(value);};
 for(const id of ['provider','weather','favorites'])$(id+'Toggle').onclick=()=>toggle(id);
 for(const id of ['google','perplexity'])$(id+'Option').onclick=()=>invoke('home.set',{homeProvider:id}).then(next=>{apply(next);close();$('query').focus();}).catch(report);
 $('voice').onclick=async()=>{const token=++voiceToken;if(listening){listening=false;invoke('home.voice.cancel').catch(()=>{});$('status').textContent='';}else{listening=true;close();$('status').textContent=t('listening');} $('voice').setAttribute('aria-pressed',String(listening));$('voice').setAttribute('aria-label',t(listening?'cancelVoice':'voice'));if(!listening)return;try{const result=await invoke('home.voice');if(!alive||token!==voiceToken)return;listening=false;$('status').textContent='';if(result.status==='recognized'&&result.text){$('query').value=result.text;await navigate(result.text);}else if(result.status!=='cancelled')$('status').textContent=t(result.status==='denied'?'denied':'voiceUnavailable');}catch{if(token===voiceToken){listening=false;$('status').textContent=t('voiceUnavailable');}}if(alive&&token===voiceToken){$('voice').setAttribute('aria-pressed','false');$('voice').setAttribute('aria-label',t('voice'));$('query').focus();}};
 document.addEventListener('pointerdown',e=>{if(open&&!$(open+'Panel').contains(e.target)&&!$(open+'Toggle').contains(e.target))close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(open){e.preventDefault();close(true);}else if(listening){e.preventDefault();$('voice').click();}}if(open==='provider'&&['ArrowUp','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();$(document.activeElement===$('googleOption')?'perplexityOption':'googleOption').focus();}if(open==='favorites'&&e.key.startsWith('Arrow')){const nodes=[...$('favoritesGrid').children],index=nodes.indexOf(document.activeElement);if(index>=0){e.preventDefault();nodes[(index+({ArrowRight:1,ArrowLeft:-1,ArrowDown:2,ArrowUp:-2}[e.key])+nodes.length)%nodes.length]?.focus();}}});
 window.addEventListener('pagehide',()=>{alive=false;++voiceToken;close();if(listening)invoke('home.voice.cancel').catch(()=>{});});invoke('home.get').then(apply).catch(report);$('query').focus({preventScroll:true});
})();
