(() => {
  'use strict';
  const ui=window.souluSettings,api=window.browserShell,{t,el,button,dialog}=ui;
  const message=error=>document.getElementById('actionMessage').textContent=error.message||error;
  const actionButton=(ru,en,fn)=>button(t(ru,en),()=>Promise.resolve().then(fn).catch(message));
  const input=(label,type='text',value='')=>{const box=el('label',undefined,'field'),n=el('input');box.append(el('span',label),n);n.type=type;n.value=value;n.setAttribute('aria-label',label);return {box,n};};
  async function guardProfileAction(fn){document.activeElement?.blur();await ui.flush();await fn();}
  async function profiles(){const state=await api.getState();dialog(t('Профили','Profiles'),box=>{for(const p of state.profiles||[]){const n=el('div',undefined,'profile-row'),text=el('span');text.append(el('b',p.name),el('small',p.active?t('Текущий профиль','Current profile'):''));n.append(text,actionButton('Открыть','Open',()=>guardProfileAction(()=>api.switchProfile(p.id))),actionButton('Подробнее','Details',()=>details(p,state.profiles.length)));n.querySelector('button').disabled=p.active;box.append(n);}});}
  function details(p,count){dialog(p.name,box=>{box.append(el('p',t('Отдельные cookies, пароли, закладки и настройки.','Separate cookies, passwords, bookmarks and settings.'),'note'));const remove=actionButton('Удалить профиль…','Delete profile…',()=>guardProfileAction(async()=>{if(!confirm(t('Будут удалены данные этого профиля с этого устройства. Продолжить?','This profile’s data will be removed from this device. Continue?')))return;await api.deleteProfile(p.id);document.getElementById('actionDialog').close();await ui.reload();}));remove.disabled=count<2||p.active;box.append(remove);if(remove.disabled)box.append(el('p',t('Нельзя удалить активный или единственный профиль.','The active or only profile cannot be deleted.'),'note'));});}
  function createProfile(){dialog(t('Создать профиль','Create profile'),box=>{const name=input(t('Название профиля','Profile name'));box.append(name.box,actionButton('Создать','Create',()=>guardProfileAction(async()=>{if(!name.n.value.trim())throw Error(t('Введите название профиля.','Enter a profile name.'));await api.createProfile(name.n.value.trim());document.getElementById('actionDialog').close();})));});}
  async function passwords(){const profile=ui.persisted?.profile;let rows=await api.getPasswords();if(!profile||ui.persisted?.profile!==profile||(await api.getState()).activeProfileId!==profile)throw Error(t('Профиль изменился. Откройте менеджер заново.','The profile changed. Reopen the manager.'));const secrets=new Set();dialog(t('Менеджер паролей','Password manager'),box=>{box.append(el('p',t('Пароли активного профиля защищены учётной записью Windows. В инкогнито пароли не сохраняются.','Passwords for the active profile are protected by your Windows account. Incognito does not save passwords.'),'note'));const search=input(t('Поиск по сайту или логину','Search site or username'),'search'),list=el('div');box.append(search.box,list);const origin=input(t('Адрес сайта','Site address'),'url'),username=input(t('Логин','Username')),secret=input(t('Пароль','Password'),'password');secret.n.autocomplete='new-password';username.n.autocomplete='off';
    function draw(){for(const n of secrets){n.value='';}secrets.clear();list.replaceChildren();for(const item of rows.filter(row=>(row.origin+' '+row.username).toLowerCase().includes(search.n.value.toLowerCase()))){const n=el('div',undefined,'profile-row credential-row'),text=el('span'),value=el('input');text.append(el('b',item.origin),el('small',item.username||t('Без логина','No username')));value.type='password';value.value='••••••••';value.readOnly=true;value.setAttribute('aria-label',t('Сохранённый пароль','Saved password'));secrets.add(value);let timer;
      const reveal=actionButton('Показать','Show',async()=>{if(value.type==='text'){value.type='password';value.value='••••••••';clearTimeout(timer);return;}value.value=await api.revealPassword(item.id);value.type='text';timer=setTimeout(()=>{value.type='password';value.value='••••••••';},15000);});
      n.append(text,value,reveal,actionButton('Копировать','Copy',async()=>{await api.copyPassword(item.id,'password');message(t('Пароль скопирован. Пока Soulu запущен, буфер очистится через 30 секунд, если его содержимое не изменится.','Password copied. While Soulu runs, the clipboard clears after 30 seconds if its content stays unchanged.'));}),actionButton('Изменить','Edit',()=>{origin.n.value=item.origin;username.n.value=item.username;secret.n.value='';secret.n.focus();}),actionButton('Удалить','Delete',async()=>{if(confirm(t('Удалить этот сохранённый пароль?','Delete this saved password?'))){rows=await api.removePassword(item.id);draw();}}));list.append(n);}if(!list.children.length)list.append(el('p',t('Записей нет','No saved passwords'),'note'));}
    search.n.oninput=draw;draw();box.append(el('h3',t('Добавить или обновить запись','Add or update an entry')),origin.box,username.box,secret.box,actionButton('Сохранить запись','Save entry',async()=>{const site=new URL(origin.n.value);if(!['http:','https:'].includes(site.protocol)||site.username||site.password)throw Error(t('Укажите HTTP/HTTPS-сайт.','Enter an HTTP/HTTPS site.'));if(rows.some(p=>p.origin===site.origin&&p.username===username.n.value)&&!confirm(t('Обновить пароль существующей записи?','Update the existing password?')))return;rows=await api.addPassword({origin:site.origin,username:username.n.value,password:secret.n.value});secret.n.value='';draw();message(t('Пароль сохранён','Password saved'));}));
    const mask=()=>{for(const n of secrets){n.type='password';n.value='••••••••';}secret.n.value='';};window.addEventListener('blur',mask);document.getElementById('actionDialog').addEventListener('close',()=>{mask();window.removeEventListener('blur',mask);},{once:true});});}
  async function importData(){const [sources,browsers,state]=await Promise.all([api.passwordSources(),api.passwordBrowsers(),api.getState()]);dialog(t('Импорт данных','Import data'),box=>{box.append(el('p',t('Импортируются локальные пароли. Закройте исходный браузер. Исходные файлы не изменяются, существующие пароли Soulu не перезаписываются. Защищённые App-Bound Encryption хранилища и Firefox с основным паролем могут быть недоступны.','Imports local passwords. Close the source browser. Source files remain unchanged and existing Soulu passwords are preserved. App-Bound Encryption stores and Firefox with a primary password may be unavailable.'),'note'));for(const b of browsers.filter(b=>b.installed))box.append(el('p',b.browser+' · '+t('Профилей: ','Profiles: ')+b.profiles));const source=el('select'),target=el('select');source.setAttribute('aria-label',t('Исходный профиль','Source profile'));target.setAttribute('aria-label',t('Целевой профиль','Target profile'));for(const s of sources)source.append(new Option(s.browser+' — '+s.name,s.id));for(const p of state.profiles)target.append(new Option(p.name,p.id));target.value=state.activeProfileId;const run=actionButton('Импортировать пароли','Import passwords',async()=>{if(!source.value||!target.value)return;if(!confirm(t('Импортировать пароли в выбранный профиль Soulu?','Import passwords into the selected Soulu profile?')))return;run.disabled=true;try{const r=await api.importPasswords({source:source.value,target:target.value});message(t(`Импортировано: ${r.imported}; пропущено: ${r.skipped}; ошибки: ${r.failed}; защищено / не поддерживается: ${r.protected}. ${r.message}`,`Imported: ${r.imported}; skipped: ${r.skipped}; failed: ${r.failed}; protected / unsupported: ${r.protected}. ${r.message}`));}finally{run.disabled=false;}});run.disabled=!sources.length;if(!sources.length)box.append(el('p',t('Поддерживаемые локальные профили не найдены.','No supported local profiles found.'),'note'));box.append(el('label',t('Исходный профиль','Source profile')),source,el('label',t('Целевой профиль','Target profile')),target,run);});}
  async function siteData(){const current=await api.getState();dialog(t('Очистить данные сайта','Clear site data'),box=>{box.append(el('p',t('Удаляется хранилище выбранного origin: localStorage, sessionStorage, IndexedDB, Cache Storage и service workers. Cookies и HTTP-кэш сохраняются. Пароли и закладки не затрагиваются. Полный список всех хранилищ пока недоступен.','Clears the selected origin’s localStorage, sessionStorage, IndexedDB, Cache Storage and service workers. Cookies and HTTP cache are preserved. Passwords and bookmarks remain unchanged. A complete list of all stores is not available.'),'note'));const seen=new Set();for(const tab of current.tabs||[]){if(tab.incognito||!/^https?:/.test(tab.url))continue;const origin=new URL(tab.url).origin;if(seen.has(origin))continue;seen.add(origin);const n=el('div',undefined,'profile-row');n.append(el('span',origin),actionButton('Очистить данные…','Clear data…',async()=>{const snapshot=await api.getSettingsSite(tab.id);if(new URL(snapshot.url).origin!==origin)throw Error(t('Страница изменилась.','The page changed.'));dialog(t('Очистить данные сайта?','Clear site data?'),confirmation=>{
 const note=el('p',t(`Удалить localStorage, sessionStorage, IndexedDB, Cache Storage и service workers для ${origin}? Cookies, HTTP-кэш, пароли и другие сайты сохранятся.`,`Remove localStorage, sessionStorage, IndexedDB, Cache Storage and service workers for ${origin}? Cookies, HTTP cache, passwords and other sites remain unchanged.`),'note');
 const cancel=actionButton('Отмена','Cancel',()=>document.getElementById('actionDialog').close());
 const clear=actionButton('Очистить','Clear',async()=>{clear.disabled=true;try{const result=await api.clearSettingsSite({tabId:snapshot.tabId,url:snapshot.url,generation:snapshot.generation,confirmed:true});message(result.cleared?t('Данные сайта очищены.','Site data cleared.'):t('Очистка отменена.','Clearing cancelled.'));}finally{clear.disabled=false;}});
 confirmation.append(note,cancel,clear);
});}));box.append(n);}if(!seen.size)box.append(el('p',t('Нет открытых сайтов в этом профиле.','No open websites in this profile.'),'note'));});}
  window.souluSettingsData={siteData,action:key=>({profileList:profiles,createProfile,passwords,import:importData}[key]?.())};
})();
