// Generated by scripts/generate-typography.py. Edit typography.json.
#pragma once
namespace soulu::typography {
struct Metrics { float size, lineHeight; int weight; };
inline constexpr float onestAscent=0.97f;
inline constexpr float onestDescent=0.305f;
inline constexpr Metrics display{32.0f,40.0f,600};
inline constexpr Metrics heading1{28.0f,36.0f,600};
inline constexpr Metrics heading2{22.0f,28.0f,600};
inline constexpr Metrics heading3{18.0f,24.0f,600};
inline constexpr Metrics bodyLarge{16.0f,24.0f,400};
inline constexpr Metrics body{14.0f,20.0f,400};
inline constexpr Metrics control{14.0f,20.0f,500};
inline constexpr Metrics compact{13.0f,18.0f,400};
inline constexpr Metrics compactControl{13.0f,18.0f,500};
inline constexpr Metrics caption{12.0f,16.0f,400};
inline constexpr Metrics menu{12.0f,16.0f,500};
inline constexpr Metrics settings1{13.0f,19.5f,400};
inline constexpr Metrics settings2{13.0f,18.2f,400};
inline constexpr Metrics settings3{21.0f,27.3f,600};
inline constexpr Metrics settings4{13.0f,18.2f,500};
inline constexpr Metrics settings5{11.5f,17.25f,400};
inline constexpr Metrics settings6{19.0f,25.65f,600};
inline constexpr Metrics settings7{12.0f,18.0f,400};
inline constexpr Metrics settings8{12.0f,18.0f,500};
inline constexpr Metrics settings9{13.0f,18.85f,400};
inline constexpr Metrics settings10{12.0f,18.6f,400};
inline constexpr Metrics settings11{18.0f,25.2f,600};
inline constexpr Metrics settings12{13.0f,19.5f,500};
inline constexpr Metrics settings13{11.0f,16.5f,400};
inline constexpr Metrics settings14{18.0f,27.0f,400};
}
